# FIREMAN PROJECT NOTEBOOK - TEP DATASET PREPROCESSING

In [1]:
import glob
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# 1 Dataset preprocessing

## 1.1 Create single dataset pandas with fault_ids, i.e. labels

In [2]:
paths = glob.glob('Tennessee_Event-Driven/datasets/d*.dat')
paths.sort()
fault_ids = [i for i in range(22) for _ in range(2)]
# extracted column names from Harward dataset
col_names = ['xmeas_1', 'xmeas_2', 'xmeas_3', 'xmeas_4', 'xmeas_5', 'xmeas_6', 'xmeas_7', 'xmeas_8', 
             'xmeas_9', 'xmeas_10', 'xmeas_11', 'xmeas_12', 'xmeas_13', 'xmeas_14', 'xmeas_15', 'xmeas_16', 
             'xmeas_17', 'xmeas_18', 'xmeas_19', 'xmeas_20', 'xmeas_21', 'xmeas_22', 'xmeas_23', 'xmeas_24', 
             'xmeas_25', 'xmeas_26', 'xmeas_27', 'xmeas_28', 'xmeas_29', 'xmeas_30', 'xmeas_31', 'xmeas_32', 
             'xmeas_33', 'xmeas_34', 'xmeas_35', 'xmeas_36', 'xmeas_37', 'xmeas_38', 'xmeas_39', 'xmeas_40', 
             'xmeas_41', 'xmv_1', 'xmv_2', 'xmv_3', 'xmv_4', 'xmv_5', 'xmv_6', 'xmv_7', 'xmv_8', 'xmv_9', 
             'xmv_10', 'xmv_11']

In [3]:
data = np.empty([0,52])
id_col = []
for file,fault_id in zip(paths,fault_ids):
    data_temp = np.genfromtxt(file)
    if 'd00.dat' in file:
        data_temp = np.rot90(data_temp)
    data = np.vstack((data, data_temp))
    id_col.extend(np.ones(len(data_temp))*fault_id)
dataset = pd.DataFrame(data=data,columns=col_names) 
dataset['fault_id'] = id_col
dataset['fault_id'] = dataset['fault_id'].astype(int)
dataset.to_csv('Tennessee_Event-Driven/datasets/dataset.csv',index=False)

## 1.2 Standard scale the dataset

In [4]:
scaler = StandardScaler()
scaler.fit(dataset[col_names])
dataset_scaled = pd.DataFrame(scaler.transform(dataset[col_names]),columns=col_names)
dataset_scaled['fault_id'] = dataset['fault_id'].copy()
dataset_scaled.to_csv('Tennessee_Event-Driven/datasets/dataset_standard_scaled.csv',index=False)
dataset_scaled.head()

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11,fault_id
0,-0.052226,1.341181,-0.205580,0.061329,0.686785,0.611956,-0.323796,0.830041,0.274466,-0.384427,...,-0.229280,-0.426554,-0.015013,-0.162950,0.865162,-0.856114,-0.036105,-0.082572,-0.030145,0
1,-0.044329,1.428249,-0.018427,0.097687,-0.784636,0.859942,-0.352796,-0.422168,0.420807,-0.405892,...,-0.234892,-0.221095,-0.043875,-0.146619,1.264180,-1.118059,-0.036766,-0.032296,-0.332347,0
2,0.162511,-0.444887,-0.104365,-0.158708,0.506161,0.394969,-0.376524,-0.370707,0.274466,-0.080116,...,-0.087726,-0.435826,0.014356,0.107020,-0.075747,-0.455944,-0.054926,-0.106529,-0.192005,0
3,0.152368,-0.906112,0.000670,-0.310876,0.312321,-0.637273,-0.396297,-0.377724,-0.018216,-0.075035,...,-0.080488,-0.226296,-0.045731,0.103233,-0.198888,0.742860,-0.060698,-0.115471,-0.076323,0
4,-0.152060,-0.788453,-0.104365,-0.212573,-0.969665,0.757648,-0.401570,0.283467,-0.457240,0.016283,...,-0.311045,-0.365041,-0.079319,0.073491,-2.739613,1.468969,-0.067493,-0.156721,-0.109552,0